# Generated by Django 4.2 on 2023-07-04 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_lookbook_image_landscape'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lookbook_image',
            name='landscape',
            field=models.BooleanField(),
        ),
    ]
