# Generated by Django 4.2 on 2023-09-15 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_product_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='orders',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=9),
        ),
    ]
