# Generated by Django 4.2 on 2023-07-30 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Youtube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subs', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('view', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
            ],
        ),
    ]
